"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const body_parser_1 = __importDefault(require("body-parser"));
require("reflect-metadata");
const dotenv_1 = __importDefault(require("dotenv"));
const user_router_1 = __importDefault(require("./routers/user.router"));
const help_router_1 = __importDefault(require("./routers/help.router"));
const helpFulfilled_router_1 = __importDefault(require("./routers/helpFulfilled.router"));
dotenv_1.default.config();
const app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use(body_parser_1.default.json());
app.use(body_parser_1.default.urlencoded({ extended: true }));
app.use("/api", [user_router_1.default, help_router_1.default, helpFulfilled_router_1.default]);
exports.default = app;
